#ifndef LEXICAL_H
#define LEXICAL_H

#include "platform.h"

#define LNG_LEXICAL_EOF 0
#define LNG_LEXICAL_FIRST LNG_LEXICAL_ID
#define LNG_LEXICAL_ID 300
#define LNG_LEXICAL_STRING 301
#define LNG_LEXICAL_NUMBER 302
#define LNG_LEXICAL_HEX 303
#define LNG_LEXICAL_GREATER_EQUAL 304
#define LNG_LEXICAL_LOWER_EQUAL 305
#define LNG_LEXICAL_GREATER_GREATER 306
#define LNG_LEXICAL_LOWER_LOWER 307
#define LNG_LEXICAL_DIFERENT 308
#define LNG_LEXICAL_EQUAL_EQUAL 309
#define LNG_LEXICAL_SUM_EQUAL 310
#define LNG_LEXICAL_SUB_EQUAL 311
#define LNG_LEXICAL_MUL_EQUAL 312
#define LNG_LEXICAL_DIV_EQUAL 313
#define LNG_LEXICAL_SUM_SUM 314
#define LNG_LEXICAL_SUB_SUB 315

#define LNG_LEXICAL_AND_WORD 316
#define LNG_LEXICAL_BOOLEAN_WORD 317
#define LNG_LEXICAL_CLASS_WORD 318
#define LNG_LEXICAL_DO_WORD 319
#define LNG_LEXICAL_DOUBLE_WORD 320
#define LNG_LEXICAL_ELSE_WORD 321
#define LNG_LEXICAL_END_WORD 322
#define LNG_LEXICAL_EXTENDS_WORD 323
#define LNG_LEXICAL_FOR_WORD 324
#define LNG_LEXICAL_FALSE_WORD 325
#define LNG_LEXICAL_FLOAT_WORD 326
#define LNG_LEXICAL_IMPLEMENTS_WORD 327
#define LNG_LEXICAL_IMPORT_WORD 328
#define LNG_LEXICAL_INTERFACE_WORD 329
#define LNG_LEXICAL_INSTANCEOF_WORD 330
#define LNG_LEXICAL_INT_WORD 331
#define LNG_LEXICAL_IF_WORD 332
#define LNG_LEXICAL_LONG_WORD 333
#define LNG_LEXICAL_OR_WORD 334
#define LNG_LEXICAL_PACKAGE_WORD 335
#define LNG_LEXICAL_PUBLIC_WORD 336
#define LNG_LEXICAL_PRIVATE_WORD 337
#define LNG_LEXICAL_PROTECTED_WORD 338
#define LNG_LEXICAL_REPEAT_WORD 339
#define LNG_LEXICAL_STRING_WORD 340
#define LNG_LEXICAL_STATIC_WORD 341
#define LNG_LEXICAL_SYNCRONIZED_WORD 342
#define LNG_LEXICAL_TRUE_WORD 343
#define LNG_LEXICAL_THROW_WORD 344
#define LNG_LEXICAL_THROWS_WORD 345
#define LNG_LEXICAL_VOID_WORD 346
#define LNG_LEXICAL_WHILE_WORD 347
#define LNG_LEXICAL_RETURN_WORD 348

struct lng_token_t {
	uint64 begin;
	uint32 size;
	uint16 type;
	uint64 line;
	uint64 column;
	byte* word;
};

struct lng_token_t* lng_lexical(const unsigned char* text, size_t* tokenSize);

void lng_lexical_test();

#endif
